name: Update Car List
on:
  schedule:
    - cron: '0 4 * * *'  # Esegue ogni giorno alle 04:00 UTC
  workflow_dispatch:    # Ti permette sempre di farlo partire a mano se serve

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python scrapingbeetest.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'AutoUpdater'
          git config --global user.email 'actions@github.com'
          git add cars.json
          git commit -m "Aggiornamento quotidiano auto" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
